- lib/pry/commands/jump_to.rb
- spec/commands/jump_to_spec.rb
Update jump_to command's spec to RSpec 3 (https://github.com/pry/pry/issues/1294)
Perform some refactorings in lib along the way.
> Refactor jump_to and its spec

- lib/pry/code/code_file.rb
Hi,
When I noticed I wasn't getting any highlighting in my Rakefile it was slightly confusing, I spent a lot of time trying to enable colors, eventually discovering that it was the Rakefile that was not supported.
So this is a small commit to enable syntax highlighting in Rakefiles and a few others.
There are no specs, as I couldn't find any existing ones around the ```CodeFile``` class. However, I can add a few if required.
Cheers,
> Enable syntax highlighting for Rakefile and other similarly named files

- lib/pry/editor.rb
- spec/editor_spec.rb
On (at least) mingw32 the manual replacement of slashes by backslashes which is removed by this PR does not work together with Shellwords.split.
Given the path `C:/foo/bar` is returned from `Pry::Editor#temp_file`. When sanitized in the current implementation it is changed to `C:\foo\bar`.
Within `Pry::Editor#open_editor`, `Shellwords.split` cripples this string to `C:foobar`.
This PR changes this to just pass the Posix-style path to windows, which is able to handle slashes on its own. Tested on Windows 2003, Windows 7, Windows 2012
> Fix edit command on windows

- lib/pry/helpers/base_helpers.rb
At the moment `not_a_real_file?` is returning true if the file path contains parentheses that surround text.
I believe the intention of the regex that I modified in this pr is to look for file paths that are entirely surrounded in parentheses or by carats like `(no_path)` or `<not_a_path>`. I fixed it to do that rather than returning true for something like `~/Dropbox (Personal)/Programming_Stuff/MyProject` where the parentheses are part of a valid path.
> Fix "not_a_real_file?" regex

- lib/pry/helpers/base_helpers.rb
The prior code was always using Pry.new.pager -- this was weird for a few reasons:
1) _pry_ is always available (afaict) so why not just call _pry_.pager rather than creating a throway pry object for this?
2) When creating a new Pry instance (via Pry.new) the when_started hook is run...this resulted in some errors and strange behaviour since a naked instance created with Pry.new is not properly configured (it misses a 'target' (binding)
I left the old code in there though to trigger when _pry_ is not available since I assume it's there for good reason?!
> Use _pry_.pager if possible

- lib/pry/history.rb
- spec/history_spec.rb
I confirm this bug in ...  
* Ubuntu 12.04 LTS  + ruby 2.0.0p0 + pry 0.10.1 env
* Windows7 + Cygwin + ruby 2.0.0p451 + pry 0.10.1 env
~~~bash
$ pry
[1] pry(main)> "hoge"
=> "hoge"
[2] pry(main)> hist --clear
History cleared.
[3] pry(main)> hist
ArgumentError: negative array size
from /home/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/pry-0.10.1/lib/pry/commands/hist.rb:171:in `last'
~~~
Not re-initialize @original_lines at `hist --clear`
~~~bash
$ pry
[1] pry(main)> "hoge"
=> "hoge"
[2] pry(main)> hist
1: "hoge"
[3] pry(main)> hist --clear
History cleared.
[4] pry(main)> hist
ArgumentError: negative array size
from /home/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/pry-0.10.1/lib/pry/commands/hist.rb:171:in `last'
[4] pry(main)> Pry.history.original_lines
=> 693
[5] …
> Fix history clear bug(No re-init @original_lines)

- lib/pry/helpers/text.rb
Addresses to #493. Fixes the described bug in the situation when you use
helper methods in your Pry prompt like this:
Pry.prompt = [
proc { |_, _, _| Pry::Helpers::Text.red("YO > ") },
proc { |_, _, _| "| "}
]
> helpers/text: respect RL_PROMPT_START_IGNORE and RL_PROMPT_END_IGNORE

- CHANGELOG.md
- lib/pry/pry_instance.rb
- lib/pry/test/helper.rb
- spec/pry_repl_spec.rb
Fixes #1369 (Prefixing commands with a space is not working)
The regression was introduced by this commit:
68bcca22a0c0f5f1e501e6316e3d51d95677542a
Since then the main logic for the REPL was hugely refactored. This
refactoring morphed the error into this commit:
e020f8cecd32fe3498790c888cc873d0f323c518
Sorry about this hacky solution.
> Fix regression with respect to space prefixes

- CHANGELOG.md
- lib/pry/command.rb
- lib/pry/command_set.rb
- lib/pry/hooks.rb
- lib/pry/pry_instance.rb
- spec/command_set_spec.rb
- spec/command_spec.rb
Fixes #651 ({after,before}_command hooks should be unified with
Pry::Hooks system)
* The support for the `Pry.commands.{after,before}_command` API was kept
* Hooks defined via the older API use random names
* The order of hooks execution was changed from LIFO to FIFO
> Refactor command hooks so they could use Pry::Hooks (newer API)

- lib/pry/config/default.rb
- lib/pry/repl.rb
Fixes https://github.com/pry/pry/issues/1334 (Pry doesn't play well with tee).
> Make Pry work with tee

- bin/pry
- lib/pry/cli.rb
- lib/pry/config/default.rb
While consuming pry programmatically in an internal project, I was surprised to discover that `parse_options` actually starts a pry session unless you mangle some internal state (clearing `option_processors`).
This patch breaks some APIs that I have no idea if there are meant to be guarantees around, so I can refactor if that's a problem, but in general causes `parse_options` to return the parsed options, which can then be passed to `start`.
> cli: parse_opts should not actually spin off a repl

- lib/pry/commands/whereami.rb
As a UNIX bod, I keep expecting to be able to type pwd to see what scope I'm in. Useful alias?
> Alias whereami to pwd

- lib/pry/repl.rb
```
warning: instance variable @readline_output not initialized
```
> Fix warning

- Rakefile
There is no need to include the CPU in the platform string as there is
no compiled code shipped in the pry gems.  The only difference is the
dependency.
Pry became a victim of rubygems/rubygems#1058 which will be fixed in
rubygems/rubygems#1120.  I would also like to raise awareness of proper
use of platform parts while I'm fixing the bug in RubyGems.
> Use CPU-less platforms for windows

- lib/pry/pry_class.rb
Following from https://github.com/pry/pry/pull/1399, updates docs and implementation of PryClass::run_command to return `nil`. I considered changing the doc to make the return value [void](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#Literals), but `nil` seemed like a more consistent result than the variable Boolean result of PryInstance#eval. Happy to change it though if this is undesirable.
> Return nil from PryClass::run_command

- lib/pry/commands/gem_readme.rb
- lib/pry/commands/play.rb
- lib/pry/repl_file_loader.rb
According to the ruby docs [File.exists](http://ruby-doc.org/core-2.2.0/File.html#method-c-exists-3F) is being deprecated.
> Changes deprecated ‘File.exists’ to ‘File.exist’

- multi_test_inside_docker.sh
* --no-rdoc and --no-ri option is deprecated.
* [gem install(command reference)](http://guides.rubygems.org/command-reference/#gem-install)
> Use --no-document option instead of --no-rdoc and --no-ri option

- spec/hooks_spec.rb
- spec/pry_spec.rb
The following warnings is displayed when you execute 'rake test'.
I fix warnings.
```ruby
naiad% rake test
--snip--
Ruby v2.2.2 (ruby), Pry v0.10.1, method_source v0.8.2, CodeRay v1.1.0, Slop v3.6.0
..........................................................................................
..........................................................................................
..........................................................................................
..........................................................................................
..........................................................................................
.......................................................................................... …
```
> Fix warning: Using the raise_error matcher without providing a specific error

- CHANGELOG.md
- lib/pry/helpers/documentation_helpers.rb
- spec/documentation_helper_spec.rb
\<tt> tags appear in documentation like CSV.foreach
> Syntax highlight <tt> tags in documentation output.

- lib/pry/cli.rb
- lib/pry/pry_class.rb
cc @kyrylo 
I tracked down the bug, it's that loading rc files and actually processing the impact of (rc files + flags) were linked.
This fixes that. I kinda poked around trying to work out how to get some tests for this, but came up blank. Let me know if it looks obvious. I did some regression testing in a shell and in an internal project that uses pry, and it looked ok.
> Split out session standup

- lib/pry/method/weird_method_locator.rb
- spec/commands/whereami_spec.rb
Hi, I found a bug when using `binding.pry` inside a method that is wrapped with a prepended method.
I'm not sure if the obtained behaviour is correct (the whereami title ends up being the module instead of the class instance), but at least fixes the infinite loop bug and provides a the minimum case to reproduce the loop.
Please let me know, if there's another way to fix it, and I can give it a try at doing it.
Thanks!
> Bug with module#prepend in ruby 2.0.0

- lib/pry/command.rb
- spec/commands/show_doc_spec.rb
When #call is defined on Symbol, Slop (3.6.0) fails. #use_unpatched_symbol is used to execute code with Symbol having its #call undefined thus preventing Slop from failing. This also fixes #1356 for facets 3.0.0
> Allow pry commands to work even when #call is defined on Symbol.

- lib/pry/pry_instance.rb
- spec/pry_repl_spec.rb
Hey. We've discussed this issue on IRC a while ago, and as far as I remember you agreed it's a good feature.
When a REPL command occupies multiple lines, currently each line is added to the history separately, which makes history navigation and editing such commands not the most pleasant experience.
This pull requests changes the behaviour to append to the history only complete expressions.
> Multiline History

- lib/pry/commands/ri.rb
When the ri command is called within a pry session, it will prompt
you to supply an argument if none is passed.
Before:
```pry
[1] pry(main)> ri
NoMethodError: undefined method `split' for nil:NilClass
from /Users/dalizard/.rubies/2.2.2/lib/ruby/2.2.0/rdoc/ri/driver.rb:1320:in `parse_name'
[1] pry(main)>
```
After:
```pry
[1] pry(main)> ri
Enter the method name you want to look up.
[2] pry(main)> 
```
> Pry::Command::Ri requires an argument

- lib/pry/commands/cat/file_formatter.rb
- spec/commands/cat_spec.rb
When cat is invoked without arguments it raises a `NoMethodError` instead of displaying an error message.
[1] pry(main)> cat
NoMethodError: undefined method `split' for nil:NilClass
from .../pry/lib/pry/commands/cat/file_formatter.rb:23:in `file_and_line'
> display an error message when cat is invoked without arguments.

- README.md
Very minor change -- when reading the README on Github, I noticed that the Ruby code example wasn't syntax highlighted.
> use ruby syntax highlighting in README

- Rakefile
Using an explicit nil like Gem::Platform.new [nil, 'mingw32'] is causing issues like https://github.com/rubygems/rubygems/issues/1120.
When pushing out new gems going forward, there shouldn't be any issues with gem platform matching.
> Explicitly set arch to 'universal' for mingw and mswin

- CHANGELOG.md
- Rakefile
- lib/pry/version.rb
@banister could you check this out and merge/release if its okay? PR is against 0-10-stable branch. Windows users can't install pry, see https://github.com/rubygems/rubygems/pull/1058 and https://github.com/rubygems/rubygems/issues/1120
> cherrypick commits to fix install of pry on Windows.

- CHANGELOG.md
- lib/pry/pry_class.rb
- spec/pry_spec.rb
adds an alternative way to the current way of setting configuration options from a pryrc file. i think its useful because it can  be used to separate modifications to `Pry.config` and other custom configurations.
```ruby
Pry.configure do |config|
config.eager_load! # optional
config.input =     # ...
config.foo = 1
end
```
> Pry configure

- CHANGELOG.md
- lib/pry/config.rb
- lib/pry/config/behavior.rb
- lib/pry/config/default.rb
- lib/pry/config/lazy.rb
- spec/config/behavior_spec.rb
- spec/config/lazy_spec.rb
adds "Pry::Config::Lazy" to make "Pry::Config::Default" less of a special case and easier to implement your own default without knowing that much internal workings.
> make 'Pry::Config::Default' less of a special case by adding Pry::Config::Lazy

- lib/pry/version.rb
Otherwise, bundler gets understandably confused when pointing to master
```
$ bundle outdated 
Fetching git://github.com/pry/pry.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Outdated gems included in the bundle:
* pry (newest 0.10.3, installed 0.10.1 b07e3f8) in group "default"
```
> Bring version up to date

- Gemfile
revert to rspec ~> 3.4.0, and simplecov ~> 0.8.0.
rspec 3.5.0 causes random test failures in the test suite.
simplecov 0.12.0 cannot be installed on ruby 1.9 or earlier.
> fix failing specs.

- README.md
This tiny change makes a tiny improvement to Pry's README and fixes the link to Gaslight's homepage.
> Fix link to Gaslight's homepage

- lib/pry/color_printer.rb
- spec/commands/ls_spec.rb
This fixes #1585 and one other build failure due to Ruby 2.4 specification change.
1. Ruby 2.4 introduces `String#pretty_print`, so we need to implicitly call Object's pretty_print where we expect the behavior not to change between Ruby versions
see: https://bugs.ruby-lang.org/issues/12664
2. There's a test case that expects 5.class to be Fixnum, but it's been changed to Integer now
see: https://bugs.ruby-lang.org/issues/12005
> Fix for Ruby 2.4 build failures

- README.md
Removed the center align tag from the logo.
Sadly Github does not support `<center>`. As of Jan 2017, because github markdown doesn't support HTML/CSS at the moment, It does allow `<br>`!
@case-eee @neight-allen
> Update Readme.md style change to allow logo

- lib/pry/color_printer.rb
[`Pry::DEFAULT_PRINT` ](https://github.com/pry/pry/blob/1f64463184e0a160d0b41d1a1f92b8e2f230278c/lib/pry.rb#L20) does a great job coloring and paging the output, but I kind of dislike the fact that it sometimes prints many short lines when it could print fewer, longer lines.
For instance, printing `(1..100).to_a` will print each number on its own line, like this:
```
[1, 
2, 
3, 
4, 
5, 
6, 
7, 
8, 
9, 
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
...
90, 
91, 
92, 
93, 
94, 
95, 
96, 
97, 
98, 
99, 
100]
```
instead of just
```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60
, 61, 62, 63, 64, 65, 66, 67, 68, …
```
> Pry::ColorPrinter.pp: add `newline` argument and pass it on to PP

- lib/pry/input_completer.rb
- spec/completion_spec.rb
This is another attempt to improve completion speed (e.g. #1540). It's a non-caching solution which improved full scan completion speed in our production app from `5s` to `0.16s`.
Even if we end up adding cache, I'd rather it didn't take long to populate.
> Improve completion speed in large applications

- .travis.yml
- CHANGELOG.md
- lib/pry.rb
- lib/pry/code.rb
- lib/pry/commands/edit.rb
- lib/pry/commands/ls.rb
- lib/pry/commands/ls/constants.rb
- lib/pry/config/behavior.rb
- lib/pry/forwardable.rb
- lib/pry/last_exception.rb
- lib/pry/method.rb
- lib/pry/output.rb
- lib/pry/pry_class.rb
- lib/pry/repl.rb
- lib/pry/slop.rb
- lib/pry/test/helper.rb
- lib/pry/wrapped_module.rb
- lib/pry/wrapped_module/candidate.rb
- spec/commands/edit_spec.rb
- spec/method_spec.rb
- spec/pry_output_spec.rb
Fix warnings and other issues that come up, eg:
```
/home/robert/.rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:225: warning: Pry::WrappedModule#respond_to?(:respond_to_missing?) uses the deprecated method signature, which takes one parameter
/home/robert/pry/lib/pry/wrapped_module.rb:153: warning: respond_to? is defined here
```
> improve ruby 2.4 support

- lib/pry/basic_object.rb
- lib/pry/config.rb
- lib/pry/config/behavior.rb
- lib/pry/input_completer.rb
- spec/completion_spec.rb
- spec/config_spec.rb
This fixes #1528.
Note: the first time the completer is invoked, `Readline.completer_word_break_characters` hasn't had its effect yet (because its value is set in the completer's constructor), but for now the user shouldn't notice that because completion for inputs like `.abc` doesn't work anymore. They'll just have to press TAB one more time.
Going forward, we should probably move that statement to the top level again, or force the construction of the completer earlier.
> Fix string literal methods completion

- CHANGELOG.md
- lib/pry/helpers/text.rb
`Pry::Helpers::Text` defines useful methods for coloring text, but it does not offer similarly for coloring the background. This PR adds that ability through methods such as `black_on_green` and `bright_cyan_on_yellow`.
I originally tried to implement it in an additive way (similar to how you can combine the `bold` helper with `red` to get text that is both bold and red), but unfortunately foreground and background colors must be defined together.
I used this approach to create [a Powerline-like Pry prompt](https://gist.github.com/SaladFork/6845b69539e06e68a3a731d1f280a777).
> Add text helpers for background colors

- CHANGELOG.md
- lib/pry/commands/change_prompt.rb
- lib/pry/commands/list_prompts.rb
- lib/pry/prompt.rb
- spec/prompt_spec.rb
A prompt added through Pry::Prompt will be visible in the output of
the "list-prompts" command, and it can be used with the "change-prompt"
command. So, adding a prompt this way integrates with the rest of Pry
and is a good option for plugins who want their prompts to be discoverable
by Pry's built-in commands.
> add Pry::Prompt.add_prompt(), Pry::Prompt.get_prompt() & Pry::Prompt.remove_prompt().

- .travis.yml
- lib/pry/core_extensions.rb
- spec/pry_spec.rb
Pull request that extends the work done by @olleolleolle for a green test suite on the
master branch. `jruby` is still part of the build matrix but if it cannot be found then we can rely on the version suggested by olle, so a release is not blocked for errors outside our control.
Thanks for PR @olleolleolle
> green JRuby on master branch.

- .travis.yml
'jruby' as a catch-all often fails (not always) but pinning to a specific
version seems to at least be able to run the test suite. Tracking JRuby
development may be best, and then pinning to a new version of JRuby when
a new version is released. It's not ideal, but at least it doesn't cause
false red flags.
> workaround JRuby CI issue.

- lib/pry/commands/whereami.rb
Current 0.11.1 gem warns with `-w` option, e.g.
`% ruby -wrpry -e ''`
> ⚠ ambiguous first argument; put parentheses or a space even after `/' operator

- CHANGELOG.md
- lib/pry/color_printer.rb
- spec/color_printer_spec.rb
This pull request fixes https://github.com/pry/pry/issues/1647 and pretty prints strings in red instead of green. This bug was introduced in https://github.com/pry/pry/pull/1586. This pull request will also continue to pretty print multi-line strings without a `'+'` delimiter, per the same pull request.
Here is a screenshot:
> Issue #1647: Fix String#pp output color

- CHANGELOG.md
Most of the previous versions used subheaders to separate features and
bugfixes. This is followup from the conversation on #1674.
> Update formatting in CHANGELOG.md

- .travis.yml
:crossed_fingers: 
~~'jruby' as a catch-all for the latest jruby appears to work again.
If this ever fails for reasons outside of our control again, I recommend
reverting this commit and considering a different CI service for jruby.~~
> Restore #1649 (sort of)

- CHANGELOG.md
- lib/pry.rb
- lib/pry/config/default.rb
- lib/pry/helpers/base_helpers.rb
- lib/pry/platform.rb
Platform is a category module that adds utility functions for querying
platform information relating to Pry.
Some methods are moved from BaseHelpers, and for backwards compatibility
included via 'include Pry::Platform'.
module_function is not used by BaseHelpers anymore, in favour of
include/extend being used in its place.
There is also less indentation noise in BaseHelpers module.
With `_pry_.h` (available on the backup master branch) these methods
exist on a single module that doesn't pollute the command scope, although
for backwards compatibility we still include the functions as top-level
command functions.
> add Pry::Platform.

- CHANGELOG.md
- lib/pry/helpers/text.rb
The &block we were capturing is not used or passed anywhere. For performance,
we shouldn't capture what we do not use.
> do not capture a Proc in Text helper methods.

- CHANGELOG.md
- lib/pry/config/behavior.rb
- lib/pry/pry_instance.rb
- spec/prompt_spec.rb
from_hash is recursive, turning Hash values into Pry::Config objects.
fix #1724
> fix a bug where "cd Hash.new" reported self as a Pry::Config in prompt.

- spec/helper.rb
As @ko1 mentioned in #1727, all the tests against Ruby 2.5 are [failing due to `NameError: uninitialized constant Pry::Forwardable`](https://travis-ci.org/pry/pry/jobs/320502644). I'm not sure why 2.5 requires an explicit `require`, but at least this will fix most of the failures.
> Fix test failures due to 'uninitialized constant Pry::Forwardable' in ruby 2.5

- CHANGELOG.md
- lib/pry/commands/clear_screen.rb
screen Pry is running in regardless of platform (Windows or UNIX-like). This change was suggested by a user and rejected by @kyrylo but I think it should be reconsidered because I have found it useful when working on Windows and UNIX-y OSes. Remembering the difference is sometimes troublesome, so I think this command is worth it.
This change was lost in the great _force push_.
Actually I have many small changes like this in bigger feature branches, such as Pry::Prompt and Pry::Deprecate, two features that would be great to eventually merge once again.
See #1624 for Pry::Prompt details.
> Add a new command, "clear-screen", that clears the content of the

- lib/pry/testable/variables.rb
This PR avoids a YARD warning.
See https://stackoverflow.com/questions/23328411/how-can-one-document-a-function-with-a-variable-number-of-arguments-in-yard for discussion of varargs in YARD.
> Avoid YARD UnknownParam warning

- lib/pry/command.rb
- lib/pry/hooks.rb
This PR changes the YARD docblocks so that warnings about `@see` are not emitted.
> Avoid YARD RedundantBraces warnings

- .travis.yml
This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/12/07/jruby-9-1-15-0.html
> Travis: JRuby 9.1.15.0

- lib/pry/history.rb
- spec/history_spec.rb
Handling failure to read or write the history file is inconsistent and can raise where it should not.
Currently for reading the file we capture _all_ errors, including some we might now. For writing the file we only capture `Errno:EACCES`.
This updates the read and write to have consistent behavior. Both rescue all `SystemCallError` classes and `Kernel#warn` with the message, then keep going.
The tests are not super nice. But any testing file IO is fragile. I settled on stubbing and expecting on some pretty specific file operations. I'd love to use something like `FakeFS`, but this fixes a bug with how `FakeFS` and `pry` work together so 🤷‍♂️ 
Closes https://github.com/fakefs/fakefs/issues/362
Fixes #1593
> Recover from any SystemCallError on failure to read or write history file

- lib/pry/method.rb
- spec/method_spec.rb
On the current version, keyword arguments get displayed with a `?`, and this PR displays them as `key_name={}` which I think is more appropriate and useful.
> support keyword args in `show-doc`

- lib/pry/code/loc.rb
- lib/pry/commands/edit.rb
- spec/code_spec.rb
- spec/commands/edit_spec.rb
As discussed here (https://github.com/pry/pry/issues/1749), the edit command doesn't push to history, and this makes it impossible to hit 'up-and-enter', that long-loved staple of REPL programming.
This PR is a surgical fix that narrowly addresses this one feature. The basic history pushing functionality is in `commands\edit.rb`, and an additional modification was also necessary to `code\loc.rb` because pushing the multiline contents of the `edit` command caused the padding in the `hist` command look messy in the following way:
With the fix applied, the history now looks as it should:
> Push edit contents to history (issue #1749)

- lib/pry/plugins.rb
Since ruby 2.5, `require 'foo'` will use the realpath of the file
corresponding to foo.rb. However `require '/absolute/path/to/foo.rb'`
won't use the realpath.
So when $GEM_HOME contains a symlink (ie it is not the realpath), when a
pry plugin is loaded, by `activate!`:
~~~ ruby
require gem_name if !active?
~~~
the real_path of `gem_name` is used.
But then in load_cli_options:
~~~ ruby
cli_options_file = File.join(spec.full_gem_path, "lib/#{spec.name}/cli.rb")
require cli_options_file if File.exist?(cli_options_file)
~~~
since the path given is absolute, it will be used directly without realpath.
This means that cli.rb may potentially be required twice (once via its realpath if the plugin requires it, the other via its $GEM_HOME path when required by `load_cli_options`), which could raise …
> PluginManager#load_cli_options: use the realpath

- CHANGELOG.md
- lib/pry/commands/show_info.rb
- lib/pry/commands/show_source.rb
- spec/commands/show_source_spec.rb
Fixes https://github.com/pry/pry/issues/1452.
($ RuntimeError.exception fails)
Alternative to https://github.com/pry/pry/pull/1453.
> commands/show_source: handle when source is nil but comment exists

- Rakefile
Commit a99861f1b1cea84d044c458ec5fba401d88c6802 broke some tests for me when I
try to run them locally. Example failures:
```
Failures:
1) gist nominally logs in
Failure/Error: expect(Pad.gist_calls[:login!]).not_to be_nil
expected: not nil
got: nil
2) show-doc on modules show-doc -a messages relating to -a indicates...
Failure/Error:
raise CommandError, "No docs found for: #{
obj_name ? obj_name : 'current context'
Pry::CommandError:
No docs found for: TestClassForShowSource
```
There's little reason to use our own task for specs since RSpec already provides
one. Switching to that deletes some old (likely unused) code and fixes the
failures for me. Win-win.
> Rakefile: unit test with help of RSpec::Core::RakeTask

- spec/commands/edit_spec.rb
This line was needed for Rubinius but since we dropped it, it serves no purpose. Thanks to @rf- for pointing out.
> spec/commands/edit: delete unwanted unlinking

- lib/pry/pry_class.rb
Note that cache file directory is not yet modified, because I don't know what to do if neither `~/.pry_history` nor `$~/.config/pry/history` is created, and `$XDG_CACHE_HOME` is not set. I'm open to discussion about that.
In addition, the specification is not fully implemented, such as this
> If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.
I don't think we need it that far, though.
Note: no idea what happened to the Travis failure.
Fixes #1316.
> Find configuration file in XDG Base Directory

- README.md
- lib/pry/cli.rb
- lib/pry/command.rb
- lib/pry/pry_class.rb
Since `~/.pryrc` was replaced by `$XDG_CONFIG_HOME` and `~/.config/pry/pryrc` in
https://github.com/pry/pry/pull/1609, we need to adjust some
documentation. `~/.pryrc` becomes simply `pryrc`.
I've also edited the wiki with this similar change.
> Tweak documentation for pryrc

- .travis.yml
- README.md
The idea is extracted from https://github.com/pry/pry/pull/1720.
This ensures that documentation mistakes don't slip through the cracks in the
future.
> travis: generate docs and fail if there are warnings

- lib/pry/helpers/text.rb
Replaces https://github.com/pry/pry/pull/1692
(Remove the "default" method from `Pry::Helpers::Text`)
This alias serves no real purpose because `bold` is already superior: it's short
and understandable.
> helpers/text: delete the 'bright_default' alias

- .circleci/config.yml
- Gemfile
CircleCI provides much faster builds than TravisCI:
CircleCI - less than 1 minute
TravisCI- 6 minutes
The cost is the complexity of the config:
https://circleci.com/docs/2.0/configuration-reference/
---
Gemfile: delete gems that were needed for Guard
`rb-inotify` has a dependency on `ffi`, which fails to compile on Ruby 1.9.3
while running on CircleCI. I don't think anyone who develops Pry (seems to be
just me so far) uses Guard in their worfklow. Our repo is missing an obligatory
Guardfile, too, which makes me think it's a very safe change to make (rather
than wasting time with`ffi` and CircleCI).
> Test with help of CircleCI

- .circleci/ruby-1.9.3p551/Dockerfile
- .circleci/ruby-2.0.0p648/Dockerfile
CircleCI doesn't provide images for these Rubies since they are no onger
suported. I had to build them manually and push to dockerhub so we can continue
testing using those Rubies.
I am committing these Dockerfiles since they belong to this project and in case
we need to modify them.
> circle: add Dockerfiles for custom Rubies

- lib/pry/core_extensions.rb
- spec/commands/cd_spec.rb
Fixes https://github.com/pry/pry/issues/1596
(Unable to inspect object built from class)
Replaces https://github.com/pry/pry/pull/1719
Big thanks to @egwspiti for the repro case and the proposed PR.
When a class redefines `respond_to?` or `method_missing` this leads to some
problems and confuses Pry. I found another example where Pry misbehaves:
```
[1] pry(main)> cd Class.new { def method_missing(*) end; def respond_to_missing?(*) true end; }.new
NoMethodError: private method `eval' called for nil:NilClass
from /Users/kyrylo/.gem/ruby/2.4.2/gems/pry-0.11.3/lib/pry/pry_instance.rb:163:in `inject_local'
```
By using `method_defined?` we can work around these bugs since this method
doesn't check whether the receiver responds to a certain message but checks
whether this method is defined (so …
> core_extensions: make '__binding__' work with redefined #respond_to?

- .rubocop.yml
- .rubocop_todo.yml
This is very opinionated and not necessary to follow.
> rubocop: disable the Style/NumericPredicate cop

- lib/pry/pry_instance.rb
I figured it's better to deprecate them to let plugin authors update their API.
> pry_instance: deprecate '#output_array' & '#input_array'

- lib/pry.rb
- lib/pry/commands/cat/input_expression_formatter.rb
- lib/pry/commands/edit.rb
- lib/pry/ring.rb
- spec/ring_spec.rb
Currently, the Ring class is written with help of Hash as backend store.
According to the comments, the implementation should behave like a circular
buffer, however it doesn't. Upon reaching maximum capacity Ring doesn't replace
old elements but keeps writing to new cells, deleting old cells, so that the
hash contains `nil` entries.
The new implementation is based on Array and seems to be closer to the actual
Ring. Older elemens get overwritten with newer ones.
This class also includes Enumerable, however none of our APIs take advantage of
it, so it seems like an overkill. There was also a problem with with this API
because of the above-mentioned nils. For example, if the ring exceeds its
maximum size, then callin `Enumerable#first` on it returns `nil`.
The new implementation deals with …
> ring: rewrite the class to improve API

- lib/pry/cli.rb
Fixes #1761 (`pry -f` can no longer suppress the loading of .pryrc)
If I recall correctly, we split session loading in #1393 because of `Pry.start`.
This broke `-f`. I think we can get away with a simple reorder in #parse_options
> cli: fix `-f` not suppressing load of `pryrc`

- lib/pry/repl.rb
Fixes #1823 (Broken upstream when rb-readline is enabled)
> repl: fix broken input while using rb-readline

- lib/pry.rb
- lib/pry/code/code_file.rb
This constant is not used anywhere else but this file so it makes sense to keep
it there.
> pry: move INITIAL_PWD to code/code_file

- lib/pry.rb
- lib/pry/cli.rb
- lib/pry/commands/shell_mode.rb
- lib/pry/commands/simple_prompt.rb
- lib/pry/config/default.rb
- lib/pry/prompt.rb
- lib/pry/pry_instance.rb
It makes a lot more sense to keep these procs under the `Pry::Prompt` namespace
than `Pry`, which is already heavily populated by other various things.
> Move prompt related code from pry.rb to prompt.rb

- lib/pry/config/default.rb
- lib/pry/prompt.rb
- lib/pry/pry_class.rb
- spec/pry_defaults_spec.rb
It makes sense to rename it because "objects" we are referring in the context of
prompt are actually prompt "contexts".
> config/default: rename prompt_safe_objects to prompt_safe_contexts

- lib/pry/config.rb
- lib/pry/prompt.rb
- lib/pry/pry_class.rb
- spec/prompt_spec.rb
Fixes #1738 (Possible to make prompt_name dynamic?)
The user-facing API is the following:
```rb
Pry.config.prompt_name = Pry.lazy { rand(100) }
[1] 80(main)>
[2] 87(main)>
[3] 30(main)>
```
> prompt: make it possible to set name dynamically

- lib/pry/command.rb
This method doesn't seem to be used anywhere, so there's no benefit in keeping
it.
> command: delete #source_location

- .circleci/config.yml
- pry.gemspec
Fixes #1804
(JRuby 9.2.0.0 breaks `source_location` and therefore our test suite)
> gemspec: bump require method_source >= 0.9.1

- lib/pry/repl.rb
Fixes #1840
(NotImplementedError: vi_editing_mode?() function is unimplemented on this
machine)
> repl: calculate JRuby overhang (or rather not)

- lib/pry/pry_instance.rb
- lib/pry/ring.rb
* ring: alias #count as #size
This is for backwards compatibility. Pry Rails uses `#size`:
https://github.com/rweng/pry-rails/blob/77f770f376077e37c69116dda39ff03ee7961f64/lib/pry-rails/prompt.rb#L23
* pry_instance: properly deprecate #{input,output}_array
Without this the warning will actually be printed on every line.
> Backport certain methods for smother transition

- lib/pry/config/default.rb
It turns out cache is supposed to be purgeable without losing information and we
don't want to lose history.
Thanks to @SirNerdBear for pointing out
(https://github.com/pry/pry/issues/1316#issuecomment-435611191)
> config/default: use XDG_DATA_HOME, not XDG_CACHE_HOME for history

- lib/pry/pager.rb
Since the top class is Pry::Pager and not Pry, the cref constant static lookup
only look for constants under Pry::Pager (or at the top level).
Since Helpers refers to Pry::Helpers, it won't be found. Fix this by
adding the correct Pry::Helpers prefix.
This fix the following bug: in SystemPager.available? the `Helpers`
constant lookup fails, so this raises an exception which is rescued and
then returns `false`; so the SimplePager is always chosen instead.
> pager.rb: fix Helpers constant invocation

- lib/pry/commands/change_prompt.rb
- lib/pry/prompt.rb
__edit: in the end this PR just fixes the syntax highlighting issue__
improvements as follows:
* GitHub, Visual Studio Code, Sublime Text Editor 2, and probably
other editors can syntax highlight prompt.rb properly now.
* Remove excessive indentation due to how we opened an module and
its singleton class (using 'class << self').
> fix syntax highlighting of prompt.rb on Github & multiple editors

- spec/commands/edit_spec.rb
It seems like JRuby has a bug with regard to exceptions being raised from within
Tempfiles: https://github.com/jruby/jruby/issues/5436
The failing specs report unexpected `/private` directory:
```
expected: "/var/folders/gk/0g887jcx5jdcdfn8fvjfmctc0000gn/T/pry20181111-62921-1ejklb.rb"
got: "/private/var/folders/gk/0g887jcx5jdcdfn8fvjfmctc0000gn/T/pry20181111-62921-1ejklb.rb"
```
The eaisest fix is to use a regexp to match the path.
> spec/commands/edit: fix failing tests when running on macOS

- lib/pry/commands/change_prompt.rb
let's try to avoid exotic heredoc syntax that GitHub and multiple
editors cannot support, the only confirmed editor that supports
highlighting this syntax so far is 'emacs'.
it is not friendly to non-emacs users to have to deal with broken
syntax highlighting, especially when there is a less exotic and
easier syntax available.
> fix syntax highlighting of change_prompt.rb

- lib/pry.rb
- lib/pry/cli.rb
- lib/pry/commands/change_prompt.rb
- lib/pry/commands/shell_mode.rb
- lib/pry/config/behavior.rb
- lib/pry/config/default.rb
- lib/pry/prompt.rb
- lib/pry/pry_instance.rb
- spec/prompt_spec.rb
- spec/pry_defaults_spec.rb
Before this change when you set a prompt, you have to do the following:
```rb
Pry.config.prompt = Pry::Prompt[:simple][:value]
```
The `[:value]` part was leaking implementation details and it proved to be an
unnecessary step.
With this change we can do the following:
```rb
Pry.config.prompt = Pry::Prompt[:simple]
```
`[:value]` is omitted.
I have also refactored some tests and removed irrelevant ones.
The Array API for prompt is deprecated:
`Pry.config.prompt = [proc {}, proc {}]` emits a warning now.
> Simplify Prompt API

- lib/pry/config/behavior.rb
- lib/pry/config/lazy.rb
- lib/pry/prompt.rb
- spec/config_spec.rb
The pry-rails prompt uses `pry.config.prompt_name` but assumes it
will be a string and never tries to `.call` the object, which means
we can end up with a prompt like this:
[2] [vagrant][development] #<Pry::Config::Lazy:0x000000000fde07b0>(main)>
This commit solves the problem for pry-rails and other prompts who make
the same mistake by calling `.call` for them, automatically.
The commit also removes the issue where every prompt has to deal with `prompt_name`
being a string / Proc-like object then acting accordingly. Now it's safe to assume
it will always be a string.
> automatically call Pry::Config::Lazy objects when read from config

- lib/pry.rb
- lib/pry/config/default.rb
- spec/helper.rb
- spec/integration/bundler_spec.rb
…ions.
The scenario:
- $ mkdir foogem
- $ cd foogem
- $ echo "source 'https://rubygems.org'" > Gemfile
- $ bundle install
- $ pry -rbundler/setup
- type `"foo".<tab>` into Pry # LoadError raised
Notice that a LoadError is raised when trying to require
"pry/input_completer". This happens because Pry is not in the
Gemfile, so once the sandbox is initialized by Bundler any require
for a Pry file is doomed to fail.
Couple that with the fact that `_pry_.config.completer` is not
read from until a user uses tab completion, and we end up in 
the situation described above.
The fix is easy and i also added a test case to confirm it works, as well as testing manually. 
I have seen this issue come up before in other issues, it can happen for example when 
loading Rails without pry being in the Rails …
> prevent LoadError being raised when using auto completions + Bundler.

- lib/pry/ring.rb
- spec/ring_spec.rb
I fixed a bug where the same value disappears when swapping parts of the array. 
example
`Pry.config.memory_size = 3`
before
```
[1] pry(main)> 1
=> 1
[2] pry(main)> 1
=> 1
[3] pry(main)> 1
=> 1
[3] pry(main)> 1
=> 1
[4] pry(main)> _pry_.input_ring.to_a
=> ["1\n"]
```
after
```
[1] pry(main)> 1
=> 1
[2] pry(main)> 1
=> 1
[3] pry(main)> 1
=> 1
[4] pry(main)> 1
=> 1
[5] pry(main)> _pry_.input_ring.to_a
=> ["1\n", "1\n", "1\n"]
```
and I fixed a bug that different values will be returned for Integer and Range.
```
[1] pry(main)> 1
=> 1
[2] pry(main)> 2
=> 2
[3] pry(main)> 3
=> 3
[4] pry(main)> 4
=> 4
```
```
[4] pry(main)> _pry_.input_ring[0]
=> "2\n"
[4] pry(main)> _pry_.input_ring[0..0]
=> "3\n"
```
> ring: fix swap parts of array in to_a and index access

- lib/pry/commands/edit/file_and_line_locator.rb
- lib/pry/commands/play.rb
- lib/pry/commands/reload_code.rb
- lib/pry/commands/whereami.rb
- lib/pry/method/weird_method_locator.rb
`eval('[__FILE__, __LINE__]')` will not work in future Ruby.
Let's stop using it when Binding#source_location is available because it
prints noisy warnings.
Since Binding#source_location is added in Ruby 2.6
https://github.com/ruby/ruby/commit/571e48b7442, this commit is leaving
old code with branching by binding.respond_to?(:source_location).
Fixes #1871
> Fix Ruby 2.6 warning for Binding#source_location

- lib/pry/cli.rb
This was mistakenly removed in 22d4ff7b22e2d2b7f49c0d883fcaefd329d2d947.
> cli: fix undefined `load_path` error

- lib/pry/commands/clear_screen.rb
- spec/commands/clear_screen_spec.rb
[1] pry(main)> clear-screen
NameError: uninitialized constant Pry::Command::ClearScreen::Helpers
Did you mean?  Pry::Helpers
[1] pry(main)> pry-version
Pry version: 0.12.2 on Ruby 2.5.1.
> Fix the 'clear-screen' command

- lib/pry/config/behavior.rb
- spec/config_spec.rb
```
Pry.config.input = RbReadline
pry(main)> _pry_.config.forget(:input)
pry(main)> _pry_.config.input
```
I ran into this issue while working on a custom input, my pry plugin set
`Pry.config.input = Custom.new(..)` and then i expected to be able to restore
Prys default (Readline) by calling `_pry_.config.forget(:input)`.
But that wasn't the case, and instead I had to do this:
```
pry(main)> Pry.config.forget(:input)
pry(main)> _pry_.config.forget(:input)
```
which isn't the expected behavior.
> Config#forget recursively removes a key from self and its default

- lib/pry/helpers/base_helpers.rb
This changes a few instances of `Pry:Helpers` to `Pry::Helpers` in base helpers deprecation warnings.
> Fix a deprecation warnings typo

- lib/pry/history.rb
- lib/pry/pry_class.rb
- spec/history_spec.rb
1. The `options` parameter may contain the `:history` key, which contains a
history array (typically `Readline::HISTORY`)
2. The `history` key is expected to have a history object as a value. Usually,
it's `Readline::HISTORY`. This object *must* be Enumerable and implement
`#clear` & `#to_a`. If nothing is provided, it defaults to an empty
array. As result, no hard dependency on `Readline` anymore.
3. Removed duplicated history objects. It looks like the original code assumed
that pushing to `Readline::HISTORY` also pushes to the file but it's not the
case. There doesn't seem to be a real need to keep two arrays of history
> Refactor Pry::History to be Readline-agnostic

- .circleci/config.yml
Ruby 2.6 has been released. 
- https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/
This patch adds Ruby 2.6 to CI.
> CI against Ruby 2.6

- pry.gemspec
`    <link rel="canonical" href="https://github.com/grosser/pry" data-pjax-transient>`
@viraptor
> make source code url the canonical url

- .rubocop_todo.yml
- CHANGELOG.md
- lib/pry/commands/show_doc.rb
- lib/pry/commands/show_source.rb
- spec/commands/show_doc_spec.rb
- spec/commands/show_source_spec.rb
Fixes #1778 (Merge show-doc and show-source together)
* `show-doc` will be printing a deprecation warning upon each invocation.
* `show-source -d` is the new way to show docs.
* in the future we could consider making `show-source -d` the default
behaviour (and introduce `--no-docs` or similar)
> Unify show-doc with show-source

- .rubocop_todo.yml
- lib/pry/code_object.rb
- lib/pry/commands/gem_stats.rb
- lib/pry/commands/ls.rb
- lib/pry/commands/ls/interrogatable.rb
- lib/pry/commands/ls/jruby_hacks.rb
- lib/pry/commands/ls/methods_helper.rb
- lib/pry/helpers/command_helpers.rb
- lib/pry/helpers/documentation_helpers.rb
- lib/pry/helpers/table.rb
- lib/pry/helpers/text.rb
- lib/pry/indent.rb
- lib/pry/input_completer.rb
- lib/pry/input_lock.rb
- lib/pry/method.rb
- lib/pry/method/patcher.rb
- lib/pry/plugins.rb
- lib/pry/pry_instance.rb
- lib/pry/rubygem.rb
- lib/pry/terminal.rb
- spec/command_spec.rb
- spec/commands/ls_spec.rb
- spec/commands/show_doc_spec.rb
- spec/commands/show_source_spec.rb
- spec/method_spec.rb
Fixes for:
* Layout/EmptyComment:
* Layout/EmptyLineAfterMagicComment:
* Layout/EmptyLinesAroundAccessModifier:
* Layout/EmptyLinesAroundExceptionHandlingKeywords:
* Layout/EmptyLinesAroundMethodBody:
* Layout/EmptyLinesAroundModuleBody:
* Layout/FirstParameterIndentation:
* Layout/IndentArray:
* Layout/IndentAssignment:
* Layout/IndentHash:
> Various rubocop fixes (2)

- .rubocop_todo.yml
- lib/pry/cli.rb
- lib/pry/commands/edit.rb
- lib/pry/commands/help.rb
- lib/pry/commands/ls.rb
- lib/pry/commands/ls/constants.rb
- lib/pry/commands/ls/instance_vars.rb
- lib/pry/commands/whereami.rb
- lib/pry/exceptions.rb
- lib/pry/helpers/table.rb
- lib/pry/input_completer.rb
- lib/pry/method.rb
- lib/pry/method/weird_method_locator.rb
- lib/pry/pry_instance.rb
- lib/pry/slop/option.rb
- lib/pry/wrapped_module.rb
- spec/command_set_spec.rb
- spec/commands/ls_spec.rb
- spec/commands/reload_code_spec.rb
- spec/commands/show_source_spec.rb
- spec/fixtures/show_source_doc_examples.rb
- spec/helper.rb
- spec/indent_spec.rb
- spec/pry_defaults_spec.rb
Fixes:
* Layout/IndentationConsistency:
* Layout/IndentationWidth:
* Layout/LeadingCommentSpace:
* Layout/MultilineArrayBraceLayout:
* Layout/MultilineHashBraceLayout:
* Layout/MultilineMethodCallBraceLayout:
* Layout/MultilineMethodCallIndentation:
* Layout/MultilineOperationIndentation:
> Fix various rubocop offences

- .rubocop_todo.yml
- lib/pry/color_printer.rb
- lib/pry/command.rb
- lib/pry/command_set.rb
- lib/pry/commands/code_collector.rb
- lib/pry/commands/gem_search.rb
- lib/pry/commands/help.rb
- lib/pry/commands/ls/local_vars.rb
- lib/pry/indent.rb
- lib/pry/input_lock.rb
- lib/pry/plugins.rb
- lib/pry/rubygem.rb
- lib/pry/slop.rb
- lib/pry/slop/commands.rb
- lib/pry/slop/option.rb
- lib/pry/testable/variables.rb
- spec/command_spec.rb
- spec/config_spec.rb
- spec/history_spec.rb
Fixes offences of the cops:
* Layout/TrailingWhitespace
* Lint/InheritException
* Performance/Casecmp
* Performance/InefficientHashSearch
* Performance/RedundantBlockCall
* Performance/RedundantMatch
* Performance/RedundantMerge
* Performance/Size
* Performance/StringReplacement
* Performance/UnneededSort
* Security/JSONLoad
> Various rubocop fixes

- .rubocop_todo.yml
- lib/pry/input_completer.rb
I am not sure what's the story behind this dead code but it is no-op and it
shouldn't harm removing it.
> rubocop: fix offences of the Lint/EmptyWhen cop

- .circleci/ruby-1.9.3p551/Dockerfile
- .circleci/ruby-2.0.0p648/Dockerfile
This is needed in case we want to compile dependencies. Without `build-base` we
will be getting errors: https://circleci.com/gh/pry/pry/6102
> circle: update Dockerfiles to have make & gcc installed

- lib/pry.rb
- lib/pry/config.rb
- spec/pry_defaults_spec.rb
Default values make sense inside config, where we already define all default
values.
> Move Pry::DEFAULT_HOOKS to Config

- lib/pry/exceptions.rb
Should've been deleted in 5ff0578f9640a1e28aa2c7f6b7beba7a6dee30f8.
I had no idea it existed here.
> exceptions: delete ExtendCommandBundle

- lib/pry/command.rb
- lib/pry/command_set.rb
- lib/pry/commands/easter_eggs.rb
- spec/command_spec.rb
Continues the removal of `install-command` started in
https://github.com/pry/pry/pull/1979.
We also delete the `nyan-cat` command because it depends on that API.
> Delete `requires_gem` remnants

- lib/pry/cli.rb
- spec/cli_spec.rb
57.14% is covered. We don't cover `on` switches because it's hard to
test them.
We also replace `exit` with `Kernel.exit` because this way we can mock this
method. Not sure why plain `exit` cannot be mocked.
> cli_spec: improve test coverage and refactor

- lib/pry/code.rb
- spec/code_spec.rb
* no more 'shoulds'
* no more 'specify'
* removed `Pry::Code#inspect` (not sure what the purpose was)
* added some new tests for methods that were never tested
* fixed #push not to accept unused and unexpected lineno
> code_spec: refactor tests to modern style

- spec/color_printer_spec.rb
I deleted some specs because I am not sure about their significance. They seemed
to be duplicative.
> color_printer_spec: refactor to modern style

- lib/pry.rb
- lib/pry/code/code_file.rb
- lib/pry/code/loc.rb
- lib/pry/color_printer.rb
- lib/pry/helpers/base_helpers.rb
- lib/pry/helpers/documentation_helpers.rb
- lib/pry/indent.rb
- lib/pry/method.rb
- lib/pry/syntax_highlighter.rb
- spec/pager_spec.rb
- spec/pry_output_spec.rb
This moves all the code related syntax highlighting and tokenization to a
wrapper class of CodeRay. Benefits:
* we reduce duplication (no need to call `scan(code, :ruby).term` everywhere)
* swapping CodeRay becomes easier because it's isolated in one class
> Factor out all CodeRay code to Pry::SyntaxHighlighter

- lib/pry/color_printer.rb
- spec/color_printer_spec.rb
I added some unit tests and made a cosmetic refactoring of ColorPrinter.
Changes:
* method extractions
* indentation fixes
* brackets for methods
* clearer variable names
There was also a bug that was introduced when I was fixing Rubocop offences: $DEFAULT_OUTPUT wasn't defined and we needed to require 'English'.
> Improve ColorPrinter and its unit tests

- CHANGELOG.md
- lib/pry.rb
- lib/pry/command_set.rb
- lib/pry/commands/disable_pry.rb
- lib/pry/commands/disabled_commands.rb
These comands were 'disabled' 6 years ago, it's about damn time to delete them.
We also delete `CommandSet#disabled_commands`. 
* the name of the method is not a verb, which is confusing
* commands have aliases
* we can deprecate commands at the place where they are defined. We would've
avoided this case with `edit-method` where the command was deprecated for
years but never removed. This is because it was deprecated using
`#disabled_commands` at an unexpected location.
>  Delete commands/disabled_commands

- lib/pry/command.rb
This was deprecated 4 years ago, so I guess it's time to remove it.
> command: delete #hooks

- lib/pry.rb
- lib/pry/config.rb
- lib/pry/editor.rb
- lib/pry/pry_class.rb
- spec/editor_spec.rb
The name strongly suggests that this method belongs to `Pry::Editor` and it
makes no sense to have it on `Pry` class.
> Move `default_editor_for_platform` to Pry::Editor

- lib/pry.rb
- lib/pry/config.rb
- lib/pry/history.rb
- spec/history_spec.rb
This makes `Pry::Config` a bit cleaner and history code is better off in
`Pry::History`, since it's probably the most expected location.
> Move history file detection to Pry::History

- lib/pry/commands/watch_expression.rb
It seems like this command defines options on the config as the user uses
Pry. This is wrong. We have command state API for this purpose. Configuration
should be done before Pry is initialized.
> commands/watch_expression: use command state instead of config

- Gemfile
v3.8.2 has a bug on Ruby 1.9.3:
https://github.com/rspec/rspec-expectations/issues/1113
```
TypeError: bind argument must be an instance of Kernel
```
Lock for now, unlock when (if) fixed version is released.
> Gemfile: lock rspec-expectations to v3.8.2

- lib/pry.rb
- lib/pry/command.rb
- lib/pry/command_state.rb
- lib/pry/control_d_handler.rb
- lib/pry/pry_instance.rb
- spec/command_spec.rb
- spec/command_state_spec.rb
- spec/commands/cd_spec.rb
- spec/commands/shell_command_spec.rb
- spec/control_d_handler_spec.rb
This change is aimed to simplify #1843 (Rework the Pry config).
Current command state implementation gets in the way. We would like to simplify
the Config class. The current implementation penetrates Pry codebase everywhere,
and during my rework of the config I discovered that `watch` uses global command
state.
It means the state should survive `Pry.new` calls. With my (unpublished yet)
implementation, the `watch` command fails to do so. I realised that we can
refactor command state implementation to be global. It makes sense to me and
also helps with the Config refactoring.
With help of a dedicated class we can easily manage the command
state (resetting).
> pry_instance: factor out command state to be global

- lib/pry/inspector.rb
- lib/pry/plugins.rb
- lib/pry/pry_class.rb
- lib/pry/pry_instance.rb
- spec/commands/cd_spec.rb
- spec/hooks_spec.rb
- spec/spec_helper.rb
This is one of preliminary steps for #1843 (Rework the Pry config).
In this commit we replace calls to `Pry::Config` where possible, therefore we
reduce coupling between the config and other components.
> Reduce the influence of Pry::Config

- lib/pry/history.rb
Fixes #2007 (Performance slowdown on entering lines)
By default, when we call `@history.count`, we actually call
`Readline::HISTORY.count`. It turns out this is a very expensive call (probably
`O(n)`). My history file has over 50k lines and calling `count` makes the
problem noticeable by spamming `Enter` as demostrated in the GIF in the issue.
We fix this issue by caching history line count and incrementing/resetting when
needed.
> history: cache @history.count to improve performance

- lib/pry/commands/show_info.rb
- lib/pry/method.rb
Fixes #2006 (show-source formatting bug in From)
In order to test this I had to build Pry from master locally and install
it. When I ran `String#initialize` I saw an error that `has_pry_doc` is
undefined on the Config class. This makes sense. This option is defined in the
pry-doc plugin.
As a workaround, I had to change the check to `defined?`. However, in the
future, we should make Pry plugin-agnostic - strictly no plugin checks in the
code.
> commands/show_info: fix formatting error for C method header

- CHANGELOG.md
- lib/pry/config.rb
- lib/pry/pry_class.rb
- spec/config_spec.rb
- spec/history_spec.rb
- spec/pryrc_spec.rb
Keeping this in a constant makes it really hard to test. Moving it to the config
and making it configurable seems to be sensible. Now we have a new option and a
lot of tests.
> config: add `rc_file` that allows specifying `pryrc` file

- lib/pry.rb
- lib/pry/command.rb
- lib/pry/prompt.rb
- lib/pry/warning.rb
- spec/warning_spec.rb
Quite often, when we deprecate APIs, we want to print a warning. Such a warning
would be hard to track without a file and line location. We are trying to be a
good citizen and print warnings like Ruby does it.
> Add Pry::Warning

- lib/pry/warning.rb
- spec/warning_spec.rb
We want to print the calling frame, so we can point out who exactly triggered
it. The current behaviour is less useful (we print the line that called the
warning).
> warning: print file and line of the calling frame

- lib/pry/config.rb
- lib/pry/control_d_handler.rb
- lib/pry/pry_instance.rb
- spec/commands/cd_spec.rb
- spec/config_spec.rb
- spec/control_d_handler_spec.rb
This is a preparational step for #1824
(Enabling `# frozen_string_literal: true` in `~/.pryc` crashes most operations)
Alternative to https://github.com/pry/pry/pull/2030
(config: delete the `control_d_handler` option)
We had to jump a few hoops to change how the handler works. The problem is that
mutation is the default expected behaviour. Therefore, we had to change its
API. There's no need to pass `eval_string` because `pry_instance` already has it
as an attribute.
`config.control_d_handler` is a proxy proc, to preserve backwards compatibility
with users of old signature (one known user is Pry Byebug). The handler will
emit a warning if the old signature is used.
> control_d_handler: don't mutate eval_string within the handler

- lib/pry/config.rb
- lib/pry/pry_class.rb
I spotted "method redefined" warnings while working with Pry in another project,
which used `--warnings`. It would be nice to enable `--warnings` in RSpec,
however it's a bit tricky because our test suite has a lot of violations (on
purpose). We should strive to fix all possible warnings, though (especially
those that occur in `lib/`).
> Resolve config warnings about redefined method

- CHANGELOG.md
- lib/pry/commands/wtf.rb
- spec/commands/wtf_spec.rb
Fixes #1876 (Make `wtf` show code)
> commands/wtf: add the --code flag

- lib/pry/color_printer.rb
- lib/pry/helpers/table.rb
- lib/pry/indent.rb
- lib/pry/pager.rb
- lib/pry/pry_class.rb
- lib/pry/terminal.rb
To be perfectly honest, I have no idea why these methods have exclamation
marks. Maybe because they may require `io/console`? Even then, there's nothing
dangerous in this.
> terminal: rename 'bang' methods to normal ones

- lib/pry/output.rb
- spec/output_spec.rb
* output: rename 'boxed_io' to 'output'
Surely, `boxed_io` sounds way cooler than plain and boring `output` but I don't
think it helps for understanding the code. Although it *is* an IO object, we
treat it as output. Hence, it should be output (no boxes involved).
* output: assign @color inside initialize
Just a shortcut, so we don't expose the whole pry_instance to all of the class.
* Add unit tests for Pry::Output
> Refactor Pry::Output and add tests

- spec/commands/edit_spec.rb
- spec/commands/show_doc_spec.rb
- spec/commands/show_source_spec.rb
- spec/commands/whereami_spec.rb
- spec/pry_spec.rb
- spec/spec_helper.rb
- spec/support/repl_tester.rb
The tests had mostly moved from `.should` to `expect(...).to eq`, but there were a few places that remained. This PR moves them over to the `expect` syntax and removes the configuration to enable the old `.should` syntax.
Rubocop did yell at me for one of the blocks being too long, so there's a few other changes in there that just turn `after do\n ... \nend` into `after { ... }` in order to shave off a few lines to appease the robot :shrug:
One that that was not obvious to me was that RSpec's `.to match whatevz` is used for both `=~` and `===` (or at least that was my conclusion, and it holds up to my experimentation, but I didn't chase it all the way down in their source, so I'm only 90% confident this is the correct way to translate these)
> Remove all remaining `.should`s from the tests

- lib/pry/repl.rb
> REPL prints to the configured output, not directly to $stdout

- spec/history_spec.rb
These tests were failing on my machine. I think it is because I have a `~/.pry_history` file. I modified them to not depend on the state of my machine.
I tried to write the helper function it in a way where you could easily test other configurations than the ones in the example (eg the existing tests don't say what should happen when the default file exists and the `XDG_DATA_PATH` exists).
On my branch:
```sh
$ git co fix-failing-tests
Your branch is up to date with 'josh/fix-failing-tests'.
$ rspec spec/history_spec.rb
...................
Finished in 0.72533 seconds (files took 0.47315 seconds to load)
19 examples, 0 failures
```
On master:
```sh
$ git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ git log -1 --pretty="%H" …
```
> Fix tests that fail based on user's environment

- lib/pry/config.rb
- lib/pry/history.rb
- spec/config_spec.rb
- spec/history_spec.rb
References #2054
Using XDG_* paths (if set) with preference higher than the
home dir, for pry config and history files.
Testing: ran `bundle exec rspec`, observed the tests pass.
> Close #2054 - prefer XDG_* paths (if set)

- spec/config_spec.rb
This spec was failing for me locally (but worked well on Circle). The reason
is that `XDG_CONFIG_HOME` is set for me and takes precedence. Therefore, the fix
would be to unset it for the test.
> spec/config: fix flaky test

- lib/pry/command.rb
- lib/pry/testable/pry_tester.rb
- spec/command_integration_spec.rb
- spec/command_spec.rb
Two tests are breaking, and I kind of understand why (the `pry_tester` command tries to evaluate them), but I'm not sure what to do about it. Figured I should commit and send a PR in hopes of another brain being able to help me out :)
It seems to behave correctly in practice, eg:
> Attempt to allow pasting multiple lines with leading dots

- pry.gemspec
This PR includes the following changes:
* gemspec: fix the 'identical summary' warning when building
* gemspec: fix the 'pessimistic dependency on coderay' warning
> Gemspec warning fixes

- lib/pry/commands/hist.rb
- spec/commands/hist_spec.rb
Remove duplicate `opts[:show]` check in hist.
Back in the day, when 10b223855e2dc073ab9eaa2c728600262c5452fb merged 645821e4d8b70db36406fa2501f57ae84e049ba0, the check for `show` and `grep` options were [moved](https://github.com/pry/pry/commit/10b223855e2dc073ab9eaa2c728600262c5452fb#diff-bfd594524f67aa64a92c2e9b84731c68R35-R37) to be checked first. However, in the original commit, [the `show` check was deleted](https://github.com/pry/pry/commit/645821e4d8b70db36406fa2501f57ae84e049ba0#diff-4a801a57f817d827c6b3449b120733a4L175-L176), while the merge commit [kept it](https://github.com/pry/pry/commit/10b223855e2dc073ab9eaa2c728600262c5452fb#diff-bfd594524f67aa64a92c2e9b84731c68R48-R49).
It seems like the only side effect of this has to do with using ranges with negative indices. For …
> Allow negative ranges in hist --show

- lib/pry/slop.rb
Recently an experimental feature has been merged in Ruby's master https://bugs.ruby-lang.org/issues/16150
In short `Symbol#to_s` will return a frozen string, whereas before it would always return a new mutable string.
Because of this `Pry::Slop#method_missing` breaks on `ruby-head`.
The fix is quite straightforward, I simply reworked the code a little bit to avoid mutating the string.
> Fix Ruby 2.7 compatibility in Pry::Slop#mehtod_missing

- .circleci/config.yml
@kyrylo as discussed in #2084, `preview2` is not yet available, and testing against `ruby-head` is not ideal because CircleCI make it hard to allow failures.
However this PR puts 2.7 testing in place, I'll try to remember to submit a PR to update `preview1` to `preview2` whenever it's available (hopefully soon).
> Test against MRI 2.7.0-preview1

- lib/pry.rb
Add an empty line after magic comments.
I wanted to check what causes build break and, when I saw what was it, I had to just simply fix it. :)
The issue happened due to reverting of an older commit. Seems like the code wasn't checked with rubocop before (or build was constantly failing or this rule was disabled) and that frozen string magic comment was added in between comment removal and reverting of that commit that removed the comment.
Either way, one empty line added, should fix the build.
> Fix: Rubocop: Layout/EmptyLineAfterMagicComment

- README.md
I just noticed that none of HTTP links in the README worked.
I've updated them to their HTTPS equivalents.
It could be that my computer some issues loading HTTP pages, but still, I believe HTTPS should be preferred when avaialable.
> Fix: Convert HTTP links to HTTPS

- CHANGELOG.md
- lib/pry/exceptions.rb
- lib/pry/pry_class.rb
Fixes #2099 ($SAFE will become a normal global variable in Ruby 3.0)
MRI < 2.7 supports `$SAFE` variable, which is associated with
taint/untaint methods. All of that is deprecated in 2.7 with a lot of
warning messages generated, and no other effect.
None of this is supported on other Ruby platforms.
Related Ruby ticket:
https://bugs.ruby-lang.org/issues/8468
> exceptions: check if $SAFE is supported by Ruby

- Gemfile
I fix belog warning in Ruby 2.7
```ruby
pry/vendor/bundle/ruby/2.7.0/gems/rake-10.5.0/lib/rake/application.rb:381: warning: deprecated Object#=~ is called on Proc; it always returns nil
```
- https://github.com/ruby/rake/pull/297
> I fix `warning: deprecated Object#=~ is called on Proc; it always returns nil` in Ruby 2.7

- README.md
Since Github no longer supports anonymous gists it would be good to either 
(the examples will fail with 
`RuntimeError: Got Net::HTTPUnauthorized from gist: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}`)
a) delete this section (like proposed in this pull request) or
b) change it with code working
> removed gist section - Readme

- pry.gemspec
This should finally fix our build on Ruby 2.7.
> gemspec: bump method_source to `~> 1.0`

- lib/pry/wrapped_module/candidate.rb
- spec/commands/whereami_spec.rb
This PR fixes the bug reported in #2052
> Fix whereami -c bug when class definition is not beginning of line

- spec/completion_spec.rb
Ref: https://github.com/pry/pry/pull/2087
The spec was failing because on 2.7 hash directly return nil without
hashing the key if they are empty:
```ruby
m = Module.new do
def self.hash; end
end
h = {}
h[m] # => nil
h[1] = 2
h[m] # => ArgumentError
```
So we need to require IRB so that the to_ignore set isn't empty.
@kyrylo
> Fix completion_spec on MRI 2.7.0

- spec/integration/bundler_spec.rb
Fixes the following warning:
```
The Gemfile specifies no dependencies
```
> spec/integration/bundler: fix the "no dependencies" warning

- CHANGELOG.md
- lib/pry/method.rb
- spec/method_spec.rb
Improves on #2086 (Directly delegate internally-used Method methods)
(we add tests here)
Description by @michaelherold
> Relying on `method_missing` for all delegation to `Method` methods means
> that it's easier for the wrong method to be called when gems mess with
> `Object` or other such core areas.
> See https://github.com/ankane/ownership/pull/3 for an example of this.
> By defining explicit delegators, at least for the methods that we use
> internally withing Pry, we can eliminate this issue and be more
> communicative around the methods on the `Pry::Method` class.
I omitted the `source_location` changes because they need some clarification.
> method: delegate internally-used methods

- CHANGELOG.md
- lib/pry/repl.rb
Fixes #1859 (Pry still leaves duplicated characters on long enough input)
> repl: clear line after indenting when Vi mode is enabled

- lib/pry/pry_instance.rb
- spec/syntax_checking_spec.rb
Previously when catching syntax errors in the REPL, we were only showing
the last syntax error displayed by the ruby output. However, ruby can
generate multiple syntax error messages within a single SyntaxException.
For example, this code generates multiple syntax error messages:
```
$ ruby -e 'puts {"key"=>"val"}.to_json'
-e:1: syntax error, unexpected =>, expecting '}'
puts {"key"=>"val"}.to_json
-e:1: syntax error, unexpected '}', expecting end-of-input
puts {"key"=>"val"}.to_json
```
We can't predict which error message would be most helpful for the
consumer - we should show both of them.
This PR modifies the string replacement we're doing when printing
syntax exceptions so any number of syntax error lines will be shown
correctly.
Previous behavior:
```
[1] pry(main)> puts …
```
> Display all syntax error messages when catching SyntaxException

- CHANGELOG.md
- lib/pry/config.rb
- spec/config_spec.rb
Returning `nil` on unknown option was default behaviour for Pry v0.12.x. In
e5556a2be8627ec3fe594c738f10422d5a1f5d43 I changed that but I am not sure if it
was intentional. This breaks plugins such as
pry-theme (https://github.com/kyrylo/pry-theme/issues/59).
Returning `nil` makes more sense, because we can write code like this:
```
Pry.config.foo ||= 123
```
...whereas as of now this is no longer possible and you would need to use
`respond_to?` to achieve the same effect.
> config: return `nil` on unknown option instead of raising

- lib/pry/command_set.rb
- lib/pry/commands/bang.rb
- spec/command_set_spec.rb
This PR improves the appearance of some of the commands in the help listing.
Previously:
```
Editing
/^\s*!\s*$/        Clear the input buffer.
Aliases
(?-mix:whereami[!?]+) Alias for `whereami`
```
Now:
```
Editing
!                  Clear the input buffer.
Aliases
/whereami[!?]+/    Alias for `whereami`
```
> Improve appearance of help command listing

- lib/pry/commands/pry_backtrace.rb
- spec/commands/pry_backtrace_spec.rb
fixes
```
pry-backtrace
RuntimeError: can't modify frozen String
from /pry-0.13.0/lib/pry/commands/pry_backtrace.rb:24:in `process'
```
> pry-backtrace frozen bug

- lib/pry/code.rb
Undefining a nonexistent definition is an error in Ruby.  This has not been a problem because there always was `Object#=~` predefined.  But we are planning to delete that useless method.  This would become an error unless properly guarded.
> do not undef =~ unless defined

- README.md
I hope all of you who maintain this gem are doing well.
I noticed that the Readme is not reporting the latest version.
This PR aims to update this information.
> Reflect latest version (0.13.1) in README

- lib/pry/commands/show_doc.rb
- lib/pry/commands/show_source.rb
`show-doc` is deprecated in favor of `show-source -d`. Updating the `?` alias accordingly.
> Update `?` alias to use show-source

- spec/integration/bundler_spec.rb
Thanks for your awesome work on maintaining pry, @kyrylo! :heart: 
However, whilst maintaining pry in Debian, I noticed that there was a test failure:
```
➜  pry git:(master) rspec spec/integration/bundler_spec.rb
Randomized with seed 32029
Traceback (most recent call last):
-e:5:in `<main>': uninitialized constant Bundler (NameError)
F
Failures:
1) Bundler when Pry requires Gemfile, which doesn't specify Pry as a dependency loads auto-completion correctly
Failure/Error: expect($CHILD_STATUS.exitstatus).to eq(42)
expected: 42
got: 1
(compared using ==)
Finished in 0.54534 seconds (files took 0.58163 seconds to load)
1 example, 1 failure
Failed examples:
rspec ./spec/integration/bundler_spec.rb:10 # Bundler when Pry requires Gemfile, which doesn't specify Pry as a dependency loads …
```
> Fix bundler_spec test

- .circleci/config.yml
- spec/syntax_checking_spec.rb
Spec started failing in ruby 3.0 because a statement which we expected to be a
syntax error is now interpreted as a valid pattern-matching statement.
Swapping the hash-rocket for a colon turns this back into a syntax
error in all ruby versions.
> Add CI support for ruby 3 and fix broken spec

- lib/pry/helpers/text.rb
- spec/commands/wtf_spec.rb
Escape non-printing characters to avoid weird behavior when colors are used.
According to https://superuser.com/questions/301353/escape-non-printing-characters-in-a-function-for-a-bash-prompt
From lib/readline/display.c:243 in bash source code:
```C
243 /* Current implementation:
244         \001 (^A) start non-visible characters
245         \002 (^B) end non-visible characters
246    all characters except \001 and \002 (following a \001) are copied to
247    the returned string; all characters except those between \001 and
248    \002 are assumed to be `visible'. */
``` 
Closes https://github.com/pry/pry/issues/493
> Escape non-printing characters

- lib/pry/helpers/text.rb
- spec/helpers/text_spec.rb
- spec/pry_repl_spec.rb
Investigating `Pry::Helpers#strip_color` I've found out that`\e[1A\e[0G` and the prompt was being removed from the text.
When the string was big enough, it wouldn't cause any trouble, as the output would just 'overwrite' it. But for strings such as 'puts "Hello"', or "'hello'.upcase" it would break the output in unexpected ways.
On master:
```
"\e[1A\e[0G[2] pry(main)> puts \e[31m\e[1;31m'\e[0m\e[31mhello\e[1;31m'\e[0m\e[31m\e[0m\e[1B\e[0G"
```
would become:
```
'hello'\e[1B\e[0G
```
With this fix:
```
"\e[1A\e[0G[2] pry(main)> puts 'hello'\e[1B\e[0G"
```
After my fix a spec on `spec/pry_repl_spec.rb:127` started failing with `RegexpError: premature end of char-class`. A simple "string".match("do\n  break #note the tab here\nend\n\e[1B\e[0G=> nil") raises an error. I've fixed that …
> Fix breakage in output with colors disabled

- CHANGELOG.md
- lib/pry/helpers/documentation_helpers.rb
- spec/documentation_helper_spec.rb
Fixes #2181 (Bad formatting)
One of the regexps matches against string that were already colored. To prevent
that I used a negative look-ahead and rejected color sequences.
> helpers/documentation: don't colorize twice

- lib/pry/cli.rb
Since changes on https://github.com/pry/pry/pull/2119 were merge we don't have the source needed to load/list plugins anymore. It was described in PR https://github.com/pry/pry/issues/2172.
Note: I also noticed we have this other PR (https://github.com/pry/pry/pull/2177) restoring plugins auto-load capabilities but considering we're waiting on `pry-byebug` to perform some changes and we may not merge that PR I'll keep this one.
> Deprecate the option "--plugins" on CLI

- README.md
it should be https://pry.github.io/ instead of https://pry.github.com
> link broken

- lib/pry/cli.rb
The `--no-history` option was almost ten years ago, in db649858a, when the object at `Pry.config.history` was still an `OpenStruct` (added in e1d9763c2, just over ten years ago!). The contract on the configuration history object changed in e5556a2be. This commit brings the `--no-history` option up to date with that refactor.
This is essentially a duplicate of #2143, but that appears to be abandoned.
> Restore `--no-history` CLI flag functionality

- CHANGELOG.md
- lib/pry/ring.rb
- spec/ring_spec.rb
Fixes #2199 (`_out_` Ring is ill-addressible)
> ring: change guard priority so that the value at index can be read

- lib/pry/config.rb
- lib/pry/pry_class.rb
- spec/config_spec.rb
Return `nil` if no default rc file is present in the filesystem.
This fixes the behavior if $XDG_CONFIG_HOME is set, but no rc file at
the path `$XDG_CONFIG_HOME/pry/pryrc` (while it may be at `~/.pryrc`).
> validates file presence in Config#default_rc_file

- lib/pry/pry_class.rb
- spec/pry_spec.rb
`Mutex#synchronize` will raise an exception if called from code passed to
`Signal.trap`. This makes it impossible to start a working Pry session
inside a signal handler.
Currently, calling `binding.pry` inside signal handling code raises an
exception because Pry uses mutexes to solve various thread-safety
issues.
This commit updates `Pry.start` to detect whether we'll have the ability
to use `Mutex#synchronize`. If not, we'll print an error message and
return instead of raising an error.
Resolves #2191
> Return with an error message if pry is started inside signal handler

- .github/workflows/test.yml
Linting wasn't running because of bad YAML.
> .github/workflows/test: fix YARD linting

- .github/workflows/test.yml
> .github/workflows/test: fix Rubocop linting

- .github/workflows/test.yml
- Gemfile
- spec/spec_helper.rb
Example failure: https://github.com/pry/pry/runs/3010680604
```
ArgumentError: wrong number of arguments (given 4, expected 1)
/home/runner/work/pry/pry/vendor/bundle/ruby/2.4.0/gems/psych-4.0.1/lib/psych.rb:323:in `safe_load'
```
I am not sure what exactly causes the failure but deleting simplecov dependency
fixes (I guess?) this problem.
> Fix failing build on Ruby 2.4 & 2.5

- .github/workflows/test.yml
Unfortunately, there's a mysterious bug with Ruby 2.4 & 2.5 when we cache gems:
https://github.com/pry/pry/actions/runs/1016360216
> .github/workflows/test: disable bundler cache

- lib/pry/core_extensions.rb
This fixes a typo in the core_extension.
> Fix typo in comment.

- README.md
The return value of `define_method` is symbol, so the return value of `def a.goodbye ... end` is `:goodbye` instead of `nil`.
https://github.com/pry/pry/blob/5590e095ae97bfed0374ee0e1f58a78dae855d8f/README.md#L209-L212
> README: Execution result of pry is one wrong

- .github/workflows/test.yml
- .rubocop.yml
Adding RUby 3.1.0 to the list of supported versions on Github Workflows
> Add Ruby 3.1 to CI

- README.md
`show-doc` is deprecated. What about a example that uses `show-source -d` instead?
https://github.com/pry/pry/blob/5590e095ae97bfed0374ee0e1f58a78dae855d8f/README.md#L342-L351
> README: Deprecated method is used in the example

- README.md
`Pry#rep` has already been removed. What about a example that uses `Pry#repl` instead?
https://github.com/pry/pry/blob/5590e095ae97bfed0374ee0e1f58a78dae855d8f/README.md#L273-L286
> README: Removed method is used in the example

- lib/pry/method.rb
The fail message is updated to include hints about what to do if the user doesn't already have `pry-doc` installed.
> Updates fail message that occurs when user doesn't have docs installed

- lib/pry/method.rb
Apologies, the line
```ruby
" and 'require pry-doc' to load it.\n"
```
should have been more like 
```ruby
" and require 'pry-doc' to load it.\n"
```
(the difference is the placement of the `'`)
In order to keep the error message formatting consistent and reduce ambiguity, this error message is amended to use backticks.
> Reduce ambiguity in error message

- .github/workflows/test.yml
- spec/commands/hist_spec.rb
- spec/editor_spec.rb
- spec/history_spec.rb
- spec/integration/cli_spec.rb
- spec/pry_repl_spec.rb
- spec/pry_spec.rb
Add partial support for testing from Ruby 2.4~2.7 on windows.
Ruby 3.0 and 3.1 should be fixed when #2209 gets merged.
This PR also aims to break down the changes on #2209 and merge it on smallers subsets. :)
> Configure Windows on Github Actions

- README.md
> Gist integration was moved into the pry-jist gem

- .github/workflows/test.yml
Updates actions/checkout to v3
pinned the jruby build 9.3.3.0. On 9.3.4.0 there's [a spec failing](https://github.com/pry/pry/blob/master/spec/commands/whereami_spec.rb#L95-L112). Which is related to https://github.com/jruby/jruby/pull/7145 . I'll dig into that into another PR. 
```
1) whereami shows description and corrects code when @method.source_location would raise an error
Failure/Error:
expect { Cor.instance_method(:blimey!).source }
.to raise_error MethodSource::SourceNotFoundError
expected MethodSource::SourceNotFoundError, got #<RuntimeError: circular causes> with backtrace:
```
> Use actions/checkout@v3

- lib/pry/method/weird_method_locator.rb
- spec/fixtures/test_task.rb
- spec/method_spec.rb
Methods that don't have a source location (e.g., C methods, or methods
created via metaprogramming or even `alias_method`) are not reasonable
possible matching methods for a "weird method" we need to locate.
In this case `renamed_method_source_location` can also return `nil` if
the actual code in question is a bare script (i.e., no methods). If that script
is loaded via `eval` then we'll end up in the weird method path in the first
place, but no method matching can be found, and if a no-source-location
method exists, we'll return that.
Down the line that's particularly painful because the source loading thinks
it's a C method, but it can actually be from metaprogramming (and `alias_method`!),
and then `Pry::Method#pry_doc_info` raises an error, and `wherami` breaks even
though we already …
> Weird method location shouldn't match unknown location

- spec/method_spec.rb
__dir__ was introduced on Ruby 2.0
> Fix ruby 1.9 build

- lib/pry/editor.rb
```
» code --help
Visual Studio Code 1.65.0
Usage: code [options][paths...]
....
-g --goto <file:line[:character]> Open a file at the path on the specified line and character position.
-w --wait                         Wait for the files to be closed before returning.
...
```
> Configure `code` as a supported editor on Pry::Editor

- lib/pry/helpers/text.rb
- spec/commands/wtf_spec.rb
Reverts pry/pry#2154
Based on discussions from https://github.com/pry/pry/pull/1582  that caused the revert of https://github.com/pry/pry/commit/d99eb05e8102cd064579a4f748e97d3d4c77b2d5 in the past which implemented a similar fix.
There are other alternatives we can explore, as done in #2209 and #2207 but for now I think reverting this is the best option.
> Revert "Escape non-printing characters"

- lib/pry/wrapped_module/candidate.rb
I was profiling gem RBI generation for [Tapioca](https://github.com/Shopify/tapioca#generating-rbi-files-for-gems) and found that it was spending half its time in `Pry::WrappedModule::Candidate#class_regexes`. I noticed that method evaluates three regexes on every invocation since [this](https://github.com/pry/pry/commit/b313a03c8f31914e510504a0f1c31df9be5ed313#diff-30f9ac3a77ff5d511bb5f9ef36e5346d34066ac7ca444f585caada0f5fec71c8R209-R211) change, and have reverted it to the prior short-circuit implementation. I've verified that tests pass locally and that the output of Tapioca RBI generation is unchanged (while running 8% faster). Tapioca has since [removed](https://github.com/Shopify/tapioca/pull/1102) the dependency on this Pry code, but I thought you might find this patch useful …
> Short circuit eval regexes in finding module definition

- .rubocop.yml
- lib/pry/basic_object.rb
- lib/pry/commands/ls/constants.rb
- lib/pry/commands/watch_expression.rb
- lib/pry/indent.rb
- lib/pry/input_completer.rb
- lib/pry/wrapped_module/candidate.rb
- pry.gemspec
- spec/commands/show_source_spec.rb
- spec/integration/cli_spec.rb
Complete rubocop todos, now that ruby 1.9.3 is no longer supported.
> Complete rubocop todos

- .github/workflows/test.yml
Why?
Currently, rubocop runs for every single ruby we test on the matrix. If rubocop fails, it fails for all jobs. 
This way, we can also unlock rubocop updates (currently fixed on 0.66.0), and also configure the TargetRubyVersion (the lowest version supported would be Ruby 2.2 though)
> Move Rubocop checks to a single GitHub Action

- .github/workflows/test.yml
Add ruby 3.2 to the test matrix, and re-enable ruby-head. 
Ruby 3.1 and 3.2 are still failing on windows. Those still need to be checked.
> Add Ruby 3.2 and head to ubuntu-latest executions

- Dockerfile
- lib/pry/helpers/platform.rb
- lib/pry/repl.rb
As a follow-up to https://github.com/pry/pry/pull/2256 this cleans up more Ruby 1.9 code
> Clean up MRI 1.9 code

- .github/workflows/test.yml
Fix the following warnings.
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
> Bump actions/checkout from 2 to 3

- lib/pry/commands/watch_expression.rb
remove arguments from `WatchExpression#add_expression` because of `# todo` https://github.com/pry/pry/blob/7642967041746d63ae37adb126687c9ec58d3faa/lib/pry/commands/watch_expression.rb#L91
> fix arguments WatchExpression#add_expression

- .github/workflows/test.yml
- spec/pry_spec.rb
Changed from ubuntu-latest to ubuntu-20. When running the 2.2 build with ubuntu 22. Bundler was not installing properly. The same does not happen with ubuntu 20. 
Ruby 2.0 tests were not running at all. It's the same issue with '3.0'. We need to add quotes to install the correct version. I also fixed a test on Ruby related to pry being called inside trap signals on Ruby 2.0. 
ruby-head is still failing. I'm take a look into that later.
> Fix Ruby 2.0 and Ruby 2.2 builds

- lib/pry/exception_handler.rb
- spec/commands/ls_spec.rb
- spec/exception_handler_spec.rb
closes https://github.com/pry/pry/issues/2280
> repair ExceptionHandler#exception_text for Ruby 3.2

- lib/pry/commands/find_method.rb
- spec/commands/find_method_spec.rb
While traversing objects and classes we may hit special objects inside constants. i.e: BasicObject.
As BasicObject does not has defined methods such as `is_a?`. We need to handle this on alternatives ways, such as Pry::Method.singleton_class_of. 
Fixes #2277
> Make find-method compatible with BasicObject instances.

- .github/workflows/test.yml
- Gemfile
- Had to downgrade psych to 5.1.0. Seems like 5.1.1 is broken on jruby.
- Had to configure terminal size on Github Actions for indentation specs.
> Make ruby-head build green again

- spec/command_set_spec.rb
remove Bond spec because optional dependency on Bond was removed in https://github.com/pry/pry/pull/1166
> remove Bond spec

- lib/pry/indent.rb
- lib/pry/method.rb
- lib/pry/syntax_highlighter.rb
When scanning code for syntax highlighting, a method 'clear' was called if defined on self.
I narrowed down the issue to being related to this part https://github.com/rubychan/coderay/blob/f71b25d3112ac7fcc43ca48055030319ecc7a840/lib/coderay/encoders/encoder.rb#L72
I changed the way we call CodeRay instead. As a part of this change, I also removed pre-coderay 1.0 code. 
Fixes #1610
> Fix 'calling clear method' when defined in pry context. 

- lib/pry/config.rb
While I was browsing the [Pry config wiki page](https://github.com/pry/pry/wiki/Customization-and-configuration#the-input-object) and the docs, I spotted a little typo, so I fixed it.
Feel free to merge if needed.
> Fix typo of input config annotation

- spec/code_spec.rb
ref: https://bugs.ruby-lang.org/issues/16495
> In Ruby 3.4 error messages are not including backticks

- .github/workflows/test.yml
Fixes warnings such as:
```[test (ubuntu-20.04, 3.2)](https://github.com/pry/pry/actions/runs/8481826392/job/23239920674)
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: actions/checkout@v3. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.```
> Update actions/checkout@v3 to actions/checkout@v4

- lib/pry.rb
- lib/pry/commands/ls.rb
- lib/pry/commands/ls/config.rb
- lib/pry/config.rb
- spec/config_spec.rb
In order to remove OpenStruct usage, I moved Ls::DEFAULT_OPTIONS on its own config class.
At first, I've tried to use a simple Struct instead, but having it be compatible between ruby versions was kinda hard and the result was not great, especially < 2.5.
> Remove OpenStruct usage from Pry::Command::Ls

- Gemfile
On https://github.com/banister/method_source/pull/80 a change was made that making <2.2 break with method_source v1.1.0.
In order to keep pry specs running, I'm pinning method_source on those builds to v1.0.0. cc @kyrylo 👀 
Few examples of that ^ 
Ruby 2.2 EOL 2018-03-31. Maybe we can consider dropping it too in the future.
> Make sure method_source stays at 1.0.0 for RUBY < 2.3

- lib/pry/pry_instance.rb
- spec/pry_defaults_spec.rb
The proc/prompt was deprecated on v0.13.0 long time ago..  on https://github.com/pry/pry/pull/1877 We should move towards using the Pry::Prompt API instead. It's also nice to remove some older code in here. 
Some projects already made their move to remove the older prompt warnings. So I think this won't be an issue. 
This also removes one type of usage do OpenStruct, which will not be loaded by Ruby 3.5.0.
> Remove deprecated Prompt proc configuration.

- lib/pry/command.rb
- lib/pry/command_state.rb
- lib/pry/commands/cd.rb
- lib/pry/commands/edit.rb
- lib/pry/commands/shell_command.rb
- lib/pry/commands/shell_mode.rb
- lib/pry/commands/watch_expression.rb
- lib/pry/control_d_handler.rb
- spec/command_spec.rb
- spec/command_state_spec.rb
- spec/commands/cd_spec.rb
- spec/commands/shell_command_spec.rb
This PR works towards removing OpenStruct usage. As ostruct will no longer be part of the default gems after Ruby 3.5. 
I am still on the fence about using command_options state to define the attributes for the Struct for each Command. Or, changing CommandState back to a Hash instead. I've checked a few plugins to see if anyone outside pry is using state directly.. But I couldn't find any.
To reduce the amount of changes and keep compatibility with other Pry Commands on this PR, I've tried to keep changes to a minimum and went with the Struct approach, and may refactor again later on.
ruby-head is still faling, as there are more OpenStruct references on the code.
> Remove OpenStruct usage from Pry::CommandState

- README.md
[warn]: In file `README.md':364: Cannot resolve link to the from text:
...{the <code>pry-rails</code> gem}...
> Fix warning when generating yard docs locally

- CHANGELOG.md
https://github.com/pry/pry/pull/2307 added support for Ruby 3.5
> CHANGELOG.md: Add support for Ruby 3.5

- .rubocop.yml
- Gemfile
On https://github.com/ruby/reline/pull/721 this warning was silenced and fixed.  I'm adding reline to our Gemfile, to make sure we're always using the most recent reline for testing.
This was causing errors on our specs on Ruby 3.3+ such as:
```
expected: "[\"1\", \"-foo\", \"--bar\", \"--baz\", \"daz\"]"
got: "/opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/reline.rb:9: warning: fiddle was loaded from the ... your Gemfile or gemspec to silence this warning.\n[\"1\", \"-foo\", \"--bar\", \"--baz\", \"daz\"]"
```
> Add reline to 3.3+ to avoid fiddle warnings

- spec/pry_repl_spec.rb
- spec/syntax_checking_spec.rb
Errors in Ruby 3.4+ are changing a bit, and we have some specs on top of a few messages.
I'm also taking the opportunity to use Prism to better validate parsing/errors. For previous versions, the code still uses eval.
> Add compatibility with ruby 3.4+ errors

- CHANGELOG.md
- Gemfile
- lib/pry/indent.rb
- lib/pry/repl.rb
On Ruby 3.3 Readline was finally replaced by reline. 
Currently pry kinda works, but has some edge cases like #2297 that were working on previous versions with Readline.
We can go back to older readline via installing `readline-ext'. [ref](https://github.com/ruby/readline-ext) As the default that come with ruby is Reline, we need some kind of support here. 
This PR attempts to add reline support, multiline editing, and so on. Making Pry compatible.
Fixes: #2063 #1524 #2297 #2302 #1740 #1765 #1514 #2023
> Add initial support for Reline on Ruby 3.3+

- lib/pry/repl.rb
Polishing a few things before releasing a new version.
I still want to improve prism usage/method_source, but I'll leave that for later.
> Fallback to Pry::Code.complete_expression? when prism is not available

- lib/pry/cli.rb
- lib/pry/config.rb
- lib/pry/repl.rb
- spec/config_spec.rb
When Reline is available, the prompt will be multiline by default.
This PR adds a CLI option --no-multiline. And config on Pry.config.multiline to allow users to fall back to single-line.
> Add --no-multiline options to disable multiline with Reline

- CHANGELOG.md
- README.md
- lib/pry/version.rb
From the CHANGELOG.md
* Added support for Reline
([#2298](https://github.com/pry/pry/pull/2298))
* Added support for Ruby 3.3
([#2295](https://github.com/pry/pry/pull/2295))
* Added Pry::Input::SimpleStdio for dumb terminals when Reline is in use
([#2304](https://github.com/pry/pry/pull/2304))
* Remove OpenStruct usage
([#2307](https://github.com/pry/pry/pull/2307))
([#2309](https://github.com/pry/pry/pull/2309))
* Disable coloring of output when NO_COLOR is set.
([#2323](https://github.com/pry/pry/pull/2323))
* Add `pry --no-multiline` flag to keep single line prompt.
([#2327](https://github.com/pry/pry/pull/2327))
* Fix typos on docs and and comments
([#2300](https://github.com/pry/pry/pull/2300))
([#2301](https://github.com/pry/pry/pull/2301))
* Fix 'calling clear method' on user code …
> Release v0.15.0

- CHANGELOG.md
- lib/pry/commands/ls/config.rb
- spec/commands/ls_spec.rb
Before #2309, Pry.config.ls was an OpenStruct which allowed colors to be accessed/mutated as a Hash or Methods.
I'm restoring compatibility and adding specs to prevent future regressions.
Fixes #2334
> Restore pry.config.ls compatibility to previous versions as a Hash

- lib/pry/repl.rb
Fix #2337 
If someone has no prism installed, the code should fallback to `Pry::Code.complete_expression?` path.
Checking if prism is installed should raise no errors.
> Avoid breaking pry when prism is not available

- CHANGELOG.md
- lib/pry/version.rb
* Restore Pry.config.ls compatibility
([#2335](https://github.com/pry/pry/pull/2335))
* Avoid breaking reading inputs if Prism is not available
([#2338](https://github.com/pry/pry/pull/2338))
> Release v0.15.1

- lib/pry/repl.rb
In case Prism was defined, but not Prism::VERSION. 
Still not sure why would prism not be available on that version. But the code will handle this scenario.
> Avoid breaking pry when prism version is not detectable

- CHANGELOG.md
- lib/pry/version.rb
This release fixes one additional scenario that could happen if prism was not available. 
* Avoid breaking reading input if Prism version is undetectable
([#2340](https://github.com/pry/pry/pull/2340))
> Prep for v0.15.2

- Gemfile
Just fixing following warning:
```
❯ bundle exec rake
: (snip)
Randomized with seed 62363
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```
> Fix warning that irb needs to be added to Gemfile

- LICENSE
- README.md
- lib/pry.rb
- lib/pry/cli.rb
Since the year following the Copyright is the year in which the work was first published, I feel that changing this would appear to not claim copyright for the period 2010-2024. So I think it is a good to change it back to the original.
see: https://github.com/pry/pry/commit/2dc06b23c8bf269be2281bf2ae8e40990e75a156
> Revert copyright year to 2010 in LICENSE, README.md, and source files
