lib/pry/plugins.rb
This change queries the plugin's gem specification to skip loading plugins that depend on a pry version the current pry does not satisfy. Pry already loads the gemspec for each gem, so this change just digs a little deeper into that info.
Closes #1312
Partially addresses #1241
=> Skip plugins which explicitly don't support current pry

lib/pry.rb
Fixes pry/pry#1330
Signed-off-by: Justin Charette <charetjc@gmail.com>
=> Fix missing require for tab completion within strings

CHANGELOG.md, lib/pry/config.rb, lib/pry/hooks.rb, lib/pry/pry_class.rb, spec/commands/watch_expression_spec.rb, spec/hooks_spec.rb
Closes https://github.com/pry/pry/issues/1392.
=> 1392 pry hooks refactoring

lib/pry/commands/whereami.rb
=> Revert "Alias whereami to pwd"

lib/pry/commands/shell_command.rb, spec/commands/shell_command_spec.rb
This is a PR by @clemenslee (he just couldn't figure out how to open one, so I did that for him).
=> Add support for CDPATH for `.cd`

CHANGELOG.md, lib/pry/commands/shell_command.rb, spec/commands/shell_command_spec.rb
The original code was confusing and had incompatible style.
=> Refactor CDPATH and its tests

lib/pry/hooks.rb
=> Hooks#add_event documentation fix

CHANGELOG.md, lib/pry/pry_class.rb, spec/pryrc_spec.rb
=> Don't raise when directory permissions don't allow file expansion.

lib/pry/indent.rb, spec/indent_spec.rb
=> singleline rescue should not change indentation.

README.md
We have rebranded as "Launch School" and have also changed domain. Thanks!
=> Tealeaf Academy is now Launch School

lib/pry/pry_instance.rb
Otherwise debugging is pretty hellish
=> log full backtrace when failing to print a value

lib/pry/pry_class.rb, spec/pry_spec.rb
=> Added support for FAIL_PRY which will make pry raise a RuntimeError if it is called with that env variable present

lib/pry/commands/show_info.rb, spec/commands/show_source_spec.rb
=> Remove exclamation point from non found method

lib/pry/code.rb, lib/pry/commands/show_info.rb, lib/pry/commands/whereami.rb, lib/pry/history.rb, lib/pry/module_candidate.rb, lib/pry/pager.rb, lib/pry/wrapped_module.rb
=> Cleanup warnings

.travis.yml
I add Ruby 2.3.1 in `.travis.yml`.
=> Test against ruby 2.3.1

lib/pry/version.rb
Just like in https://github.com/pry/pry/pull/1510.
=> Bring version up to date

lib/pry/helpers/colors.rb, lib/pry/pry_instance.rb
```
pry(main)> puts _pry_.helpers.green("Yo!")
```
@mvz #1633
=> add Pry#helpers, fix #1634

lib/pry/commands/easter_eggs.rb
=> add poem (see http://stdout.io for source of message)

lib/pry/helpers/base_helpers.rb
Like described in
https://github.com/pry/pry/issues/1660 a simple
change fixes pry
=> Fix issue #1660, pry output error in base_helpers

CHANGELOG.md, lib/pry/helpers/text.rb
Thanks to @SaladFork. 
This is a feature we should not throw away.
=> Add text helpers for background colors

.travis.yml
add new JRuby to the Travis matrix.
=> jruby-9.1.14.0

Rakefile
=> Update Rakefile to properly run specs

lib/pry/version.rb
need to bump version before release
=> bump version

Gemfile
Fixes https://github.com/pry/pry/issues/1557
=> Update RSpec version to 3.7

lib/pry/input_completer.rb
Set is not always loaded already (oops).
=> Fix full scan completion in bare pry

lib/pry.rb, lib/pry/commands/wtf.rb, spec/commands/wtf_spec.rb
Fixes #1449 (support exceptions with cause)
Replaces #1525
=> commands/wtf,pry: add support for Exception#cause

lib/pry/repl.rb
This improves on https://github.com/pry/pry/pull/1813.
I spotted a problem with the way it works: sometimes, if you enter an empty
line, the output would span across two lines:
```
[1] pry(main)>
[2] pry(main)>
[3] pry(main)>
```
This is because overhang is bigger than the current line. I also noticed a bug
with method definition, where defining a method leaves an unwanted empty line:
```
[3] pry(main)> def foo
| end
=> :foo
```
To fix this I changed the way we calculate overhang. First and the most
important change is that I stopped calculating overhang for emacs mode. This is
because it's too risky to introduce this change because it's the default mode
and 99% of our users use this, so there's no need to change this
behaviour. Another reason is that emacs mode users typically don't use …
=> repl: correctly calculate overhang for empty lines

lib/pry/config/default.rb, lib/pry/history.rb
Fixes #1316
(support XDG Base Directory Specification)
=> config/default: add support for $XDG_CACHE_HOME for history

CHANGELOG.md
This PR should be merged when we are ready to release next Pry version. It should be updated with new entries when needed. I find this technique better than making 1 PR per 1 CHANGELOG entry.
Ideally, a PR that adds some functionality should also update the CHANGELOG, however I believe it's too much to ask from contributors.
=> Update CHANGELOG for the next release

lib/pry/version.rb
Fixes #1776 (Let's release v0.12.0)
=> Release v0.12.0

pry.gemspec
Add metadata links for quick access from the RubyGems catalogue.
=> Add rubygems metadata

README.md
* Add the main title (project name)
* Tweak markup
* Tweak wording for introduction
It still needs a major refresh but that will be addressed later.
=> README: refresh the top part

.rubocop.yml, lib/pry/config/behavior.rb
i only intended to add/update API docs but discovered a bug in eager_load!
while doing that, so i fixed that at the same time.
__edit: opening a different PR with the bug fix__
=> Add API documentation for Pry::Config

lib/pry/pry_class.rb
=> Update link to Readline fix

README.md, lib/pry/commands/cat/exception_formatter.rb, lib/pry/commands/show_info.rb, lib/pry/commands/whereami.rb, spec/commands/whereami_spec.rb
This is how Ruby formats line numbers. It's more concisce and it is still
understandable.
=> Change formatting of "file.rb @ line 1" to "file.rb:1"

README.md
* Wrap everything at 80 characters
* Delete outdated info with "future" plans
* Add better structure to the document
=> README: refresh content, add more structure

.rubocop.yml, .rubocop_todo.yml, lib/pry/cli.rb, lib/pry/commands/cat/abstract_formatter.rb, lib/pry/commands/cat/exception_formatter.rb, lib/pry/commands/cat/input_expression_formatter.rb, lib/pry/commands/easter_eggs.rb, lib/pry/commands/gem_stats.rb, lib/pry/commands/show_doc.rb, lib/pry/helpers/documentation_helpers.rb, lib/pry/helpers/options_helpers.rb, lib/pry/input_completer.rb, lib/pry/wrapped_module.rb, spec/command_integration_spec.rb, spec/command_spec.rb, spec/commands/show_source_spec.rb, spec/commands/whereami_spec.rb, spec/completion_spec.rb, spec/history_spec.rb, spec/method/patcher_spec.rb, spec/pry_defaults_spec.rb, spec/sticky_locals_spec.rb
Fixes for:
* Layout/BlockEndNewline
* Layout/ClosingHeredocIndentation
* Layout/ClosingParenthesisIndentation
* Layout/CommentIndentation
* Layout/DotPosition
=> Various rubocop fixes

.rubocop.yml, Gemfile, spec/spec_helper.rb
* Update the requirement to latest version
* Make sure we actually *check* code coverage. Previously, we were only checking
files in `spec/`, but not we also check `lib/`
=> Make SimpleCov check the lib directory

lib/pry.rb, lib/pry/config.rb, lib/pry/inspector.rb, spec/commands/cd_spec.rb, spec/control_d_handler_spec.rb, spec/pry_output_spec.rb
Default values make sense inside config, where we already define all default
values.
=> Move "DEFAULT" constants to Config

spec/code_object_spec.rb
We try to use RSpec features and anonymous classes whenever we can. The tests
are easier to read now as well.
=> code_object_spec: refactor to modern syntax; make more legible

lib/pry/command_set.rb, spec/command_set_spec.rb
In this change we:
* Used modern RSpec API
* Deleted unused methods
=> command_set: refactor specs

lib/pry/commands/wtf.rb, spec/commands/wtf_spec.rb
* commands/wtf_spec: refactor unit tests
Although this is more verbose now, it looks more like proper unit tests. The
tester API needs to be revamped because `tester.eval` is *not* unit testing.
* commands/wtf: refactor to avoid duplication
=> Refactoring of 'wtf' and its tests

lib/pry/commands/easter_eggs.rb
See issue #2049 for more details.
=> Remove exclusionary easter egg command

lib/pry/config/memoized_value.rb, spec/config/memoized_value_spec.rb
I moved the existing `subject` into the test because it didn't make sense for the second test I added.
=> MemoizedValue memoizes nil results

lib/pry.rb, lib/pry/commands/shell_command.rb, lib/pry/config.rb, lib/pry/editor.rb, lib/pry/env.rb, lib/pry/helpers/base_helpers.rb, lib/pry/helpers/platform.rb, lib/pry/history.rb, lib/pry/output.rb, lib/pry/pager.rb, lib/pry/pry_class.rb, spec/config_spec.rb, spec/env_spec.rb, spec/output_spec.rb, spec/pry_spec.rb
Env is a helper module to work with environment variables.
=> Add Pry::Env and use where it makes sense

lib/pry/commands/edit/file_and_line_locator.rb
Thanks for the catch:
https://github.com/pry/pry/commit/272b3290b5250d28ee82a5ff65aa3b29b825e37b#commitcomment-36938715
=> commands/edit/file_and_line_locator: refactor eval expression

CHANGELOG.md
Updated the CHANGELOG.md with the relevant changes and bug fixes added after the last release.
=> Update CHANGELOG.md to reflect the latest master changes

README.md
pry-rails is not currently maintained, so I'm adding this disclaimer to the README.
Closes #2255
=> Add disclaimer about pry-rails not being currently maintained

CHANGELOG.md, lib/pry/pry_class.rb, spec/pry_spec.rb
Fixes https://github.com/pry/pry/issues/2260
=> Respect NO_COLOR ENV when present
